
[soul_catcher]
	#Entity ids that should not be capturable
	entity_blacklist = ["minecraft:iron_golem", "minecraft:snow_golem", "minecraft:warden"]
	#Maximum distance at which entities can be captured
	#Range: 5.0 ~ 50.0
	max_distance = 15.0
	#Entity health needs to be at or below this percentage to be able to be caught
	#1.0 = 100% -> Entities can be caught at full health
	#0.0 = Entities can only be caught at half a heart
	#Range: 0.0 ~ 1.0
	max_health_percentage = 1.0

[mechanical_spawner]
	#Maximum stress impact (impact scales with entity health)
	#Range: 1.0 ~ 1.7976931348623157E308
	max_stress_impact = 80.0
	#Minimum RPM required to progress
	#Range: 1.0 ~ 1.7976931348623157E308
	min_rpm = 128.0

